server:
  port: 8930

spring:
  application:
    name: usuario-service

  datasource:
    url: jdbc:oracle:thin:@207.231.108.32:49161/xe
    username: apex_us_dsy_08_cool_dino
    password: macarena

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka