server:
  port: 8910 #puerto para dependencia del microservicio

spring:
  application:
    name: pedido-service

  datasource: #datos de nuestra base de datos
    url: jdbc:oracle:thin:@207.231.108.32:49161/xe
    username: apex_us_dsy_08_cool_dino
    password: macarena

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka

     